<?xml version="1.0" ?>

<robot name="skidsteer" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo reference="link_chassis">
    <material>Gazebo/Green</material>
  </gazebo>
  <gazebo reference="link_front_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="link_front_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="link_back_right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="link_back_left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>
  
  <gazebo>
      <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
      <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
      <leftRearJoint>back_left_wheel_joint</leftRearJoint>
      <rightRearJoint>back_right_wheel_joint</rightRearJoint>
      <wheelSeparation>0.3</wheelSeparation>
      <wheelDiameter>0.2</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>20</torque>
      <topicName>cmd_vel</topicName>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>

  <xacro:arg name="gpu" default="false"/>
  <xacro:property name="gpu" value="$(arg gpu)" />
  <xacro:arg name="organize_cloud" default="false"/>
  <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />
    
<!-- <gazebo> -->
<!--   <sensor type="gpu_ray" name="HDL32E"> -->
<!--     <visualize>true</visualize> -->
<!--     <update_rate>10</update_rate> -->
<!--     <ray> -->
<!--       <scan> -->
<!--         <horizontal> -->
<!--           <samples>2187</samples> -->
<!--           <resolution>1</resolution> -->
<!--           <min_angle>3.14</min_angle> -->
<!--           <max_angle>3.14</max_angle> -->
<!--         </horizontal> -->
<!--         <vertical> -->
<!--           <samples>32</samples> -->
<!--           <resolution>1</resolution> -->
<!--           <min_angle>-${30.67*3.14/180.0}</min_angle> -->
<!--           <max_angle> ${10.67*3.14/180.0}</max_angle> -->
<!--         </vertical> -->
<!--       </scan> -->
<!--       <range> -->
<!--         <min>0.3</min> -->
<!--         <max>131</max> -->
<!--         <resolution>0.001</resolution> -->
<!--       </range> -->
<!--       <noise> -->
<!--         <type>gaussian</type> -->
<!--         <mean>0.0</mean> -->
<!--         <stddev>0.0</stddev> -->
<!--       </noise> -->
<!--     </ray> -->
<!--     <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_velodyne_gpu_laser.so"> -->
<!--       <topicName>/velodyne_points</topicName> -->
<!--       <frameName>laz_base</frameName> -->
<!--       <organize_cloud>false</organize_cloud> -->
<!--       <min_range>0.9</min_range> -->
<!--       <max_range>130</max_range> -->
<!--     </plugin> -->
<!--   </sensor> -->
<!-- </gazebo> -->

  <link name="link_chassis">
    <!-- pose and inertial -->
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0.1"/>
      <inertia ixx="0.40833333333333" ixy="0" ixz="0" iyy="0.24166666666667"
        iyz="0" izz="0.24166666666667"/>
    </inertial>
    <!-- body -->
    <collision>
      <geometry>
        <box size="0.5 0.5 0.08"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.5 0.5 0.08"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>
  
  <!-- defining wheels -->

  <link name="link_front_right_wheel">
    <inertial>
      <mass value="0.2"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <inertia ixx="0.0126666666666667" ixy="0" ixz="0" iyy="0.0126666666666667"
        iyz="0" izz="0.025"/>
    </inertial>
    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </collision>
    <visual name="link_front_right_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </visual>
  </link>

  <link name="link_front_left_wheel">
    <inertial>
      <mass value="0.2"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <inertia ixx="0.0126666666666667" ixy="0" ixz="0" iyy="0.0126666666666667"
        iyz="0" izz="0.025"/>
    </inertial>
    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </collision>
    <visual name="link_front_left_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </visual>
  </link>

  <link name="link_back_right_wheel">
    <inertial>
      <mass value="0.2"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <inertia ixx="0.0126666666666667" ixy="0" ixz="0" iyy="0.0126666666666667"
        iyz="0" izz="0.025"/>
    </inertial>
    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </collision>
    <visual name="link_back_right_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </visual>
  </link>

  <link name="link_back_left_wheel">
    <inertial>
      <mass value="0.2"/>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <inertia ixx="0.0126666666666667" ixy="0" ixz="0" iyy="0.0126666666666667"
        iyz="0" izz="0.025"/>
    </inertial>
    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </collision>
    <visual name="link_back_left_wheel_visual">
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.1"/>
    </geometry>
    </visual>
  </link>


  <!-- defining joints -->

  <joint name="front_right_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0.27 0.27 0"/>
    <child link="link_front_right_wheel"/>
    <parent link="link_chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="100" velocity="1"/>
  </joint>
  
  <joint name="front_left_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0.27 -0.27 0"/>
    <child link="link_front_left_wheel"/>
    <parent link="link_chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="100" velocity="1"/>
  </joint>

  <joint name="back_right_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-0.27 0.27 0"/>
    <child link="link_back_right_wheel"/>
    <parent link="link_chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="100" velocity="1"/>
  </joint>
  
  <joint name="back_left_wheel_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-0.27 -0.27 0"/>
    <child link="link_back_left_wheel"/>
    <parent link="link_chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="100" velocity="1"/>
  </joint>

  <!-- <xacro:property name="base_radius" value="0.05"/> -->
  <!-- <xacro:property name="base_height" value="0.05"/> -->
  <!-- <xacro:property name="laz_radius" value="0.04"/> -->
  <!-- <xacro:property name="laz_height" value="0.1"/> -->
  <!--  -->
  <!-- <link name="laz_base"> -->
  <!--   <visual> -->
  <!--     <geometry> -->
  <!--       <cylinder length="${base_height}" radius="${base_radius}"/> -->
  <!--     </geometry> -->
  <!--   </visual> -->
  <!--  -->
  <!--   <collision> -->
  <!--     <geometry> -->
  <!--       <cylinder length="${base_height}" radius="${base_radius}"/> -->
  <!--     </geometry> -->
  <!--   </collision> -->
  <!--  -->
  <!--   <inertial> -->
  <!--     <mass value="0.1"/> -->
  <!--     <inertia ixx="${(1/12) * 0.1 * (3 * base_radius * base_radius + base_height * base_height)}" ixy="0" ixz="0" iyy="${(1/12) * 0.1 * (3 * base_radius * base_radius + base_height * base_height)}" iyz="0" izz="${(1/2) * 0.1 * base_radius * base_radius}"/> -->
  <!--   </inertial> -->
  <!-- </link> -->
  <!--  -->
  <!-- <link name="laz_rot"> -->
  <!--   <visual> -->
  <!--     <geometry> -->
  <!--       <cylinder length="${laz_height}" radius="${laz_radius}"/> -->
  <!--     </geometry> -->
  <!--   </visual> -->
  <!--  -->
  <!--   <collision> -->
  <!--     <geometry> -->
  <!--       <cylinder length="${laz_height}" radius="${laz_radius}"/> -->
  <!--     </geometry> -->
  <!--   </collision> -->
  <!--  -->
  <!--   <inertial> -->
  <!--     <mass value="0.1"/> -->
  <!--     <inertia ixx="${(1/12) * 0.1 * (3 * laz_radius * laz_radius + laz_height * laz_height)}" ixy="0" ixz="0" iyy="${(1/12) * 0.1 * (3 * laz_radius * laz_radius + laz_height * laz_height)}" iyz="0" izz="${(1/2) * 0.1 * laz_radius * laz_radius}"/> -->
  <!--   </inertial> -->
  <!-- </link> -->
  <!--  -->
  <!-- <joint name="lazRot" type="continuous"> -->
  <!--   <parent link="laz_base"/> -->
  <!--   <child link="laz_rot"/> -->
  <!--   <axis xyz="0 0 1"/> -->
  <!--   <origin xyz = "0 0 ${base_height/2}"/> -->
  <!-- </joint> -->

  <!-- <joint name="lidarGlue" type="fixed"> -->
  <!--   <origin rpy="0 0 0" xyz="0.1 0 0.05"/>      -->
  <!--   <parent link="link_chassis"/> -->
  <!--   <child link="laz_base"/> -->
  <!-- </joint> -->

  <xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.urdf.xacro"/>
  <xacro:HDL-32E parent="link_chassis" name="velodyne2" topic="/velodyne_points2" organize_cloud="${organize_cloud}" hz="10" samples="220" gpu="${gpu}">
    <origin xyz="0 0.1 0.05" rpy="0 0 0" />
  </xacro:HDL-32E>

</robot>
